
name: CI/CD

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    env:
      NODE_PATH: src/
      CI: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Install dependencies
      run: npm install

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage --updateSnapshot
    
    - name: Trufflehog Actions Scan
      uses: edplato/trufflehog-actions-scan@v0.9i-beta

    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        token: 02aedf07-d29d-4f8f-b343-6b647e5a737d
        
    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@0.2.0
      with:
        project-token: 50e306f95c464eeba4ceaaf2af56af4a

    - name: Build
      run: npm run build
